In [29]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [30]:
df1 = pd.read_csv('train.csv')
df1.head()

,respondent_id,xyz_vaccine,seasonal_vaccine,xyz_concern_0.0,xyz_concern_1.0,xyz_concern_2.0,xyz_concern_3.0,xyz_knowledge_0.0,xyz_knowledge_1.0,behavioral_antiviral_meds_0.0,...,employment_status_Unemployed,"census_msa_MSA, Principle City",census_msa_Non-MSA,household_adults_0.0,household_adults_2.0,household_adults_3.0,household_children_0.0,household_children_1.0,household_children_2.0,household_children_3.0
0,0,0,0,False,True,False,False,True,False,True,...,False,False,True,True,False,False,True,False,False,False
1,1,0,1,False,False,False,True,False,False,True,...,False,False,False,True,False,False,True,False,False,False
2,2,0,0,False,True,False,False,False,True,True,...,False,False,False,False,True,False,True,False,False,False
3,3,0,1,False,True,False,False,False,True,True,...,False,True,False,True,False,False,True,False,False,False
4,4,0,0,False,False,True,False,False,True,True,...,False,False,False,False,False,False,True,False,False,False

In [31]:
from sklearn.model_selection import train_test_split

# Define features and target variables
X = df1.drop(columns=['respondent_id', 'xyz_vaccine', 'seasonal_vaccine'])
y = df1[['xyz_vaccine', 'seasonal_vaccine']]

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=707)

In [32]:
X.head()

,xyz_concern_0.0,xyz_concern_1.0,xyz_concern_2.0,xyz_concern_3.0,xyz_knowledge_0.0,xyz_knowledge_1.0,behavioral_antiviral_meds_0.0,behavioral_avoidance_0.0,behavioral_face_mask_0.0,behavioral_wash_hands_0.0,...,employment_status_Unemployed,"census_msa_MSA, Principle City",census_msa_Non-MSA,household_adults_0.0,household_adults_2.0,household_adults_3.0,household_children_0.0,household_children_1.0,household_children_2.0,household_children_3.0
0,False,True,False,False,True,False,True,True,True,True,...,False,False,True,True,False,False,True,False,False,False
1,False,False,False,True,False,False,True,False,True,False,...,False,False,False,True,False,False,True,False,False,False
2,False,True,False,False,False,True,True,False,True,True,...,False,False,False,False,True,False,True,False,False,False
3,False,True,False,False,False,True,True,False,True,False,...,False,True,False,True,False,False,True,False,False,False
4,False,False,True,False,False,True,True,False,True,False,...,False,False,False,False,False,False,True,False,False,False

In [33]:
df2 = pd.read_csv('test.csv')
df2.head()

,respondent_id,xyz_concern_0.0,xyz_concern_1.0,xyz_concern_2.0,xyz_concern_3.0,xyz_knowledge_0.0,xyz_knowledge_1.0,xyz_knowledge_2.0,behavioral_antiviral_meds_0.0,behavioral_antiviral_meds_1.0,...,"census_msa_MSA, Principle City",census_msa_Non-MSA,household_adults_0.0,household_adults_1.0,household_adults_2.0,household_adults_3.0,household_children_0.0,household_children_1.0,household_children_2.0,household_children_3.0
0,26707,False,False,True,False,False,False,True,True,False,...,False,False,False,True,False,False,True,False,False,False
1,26708,False,True,False,False,False,True,False,True,False,...,False,True,False,False,False,True,True,False,False,False
2,26709,False,False,True,False,False,False,True,True,False,...,False,True,False,True,False,False,True,False,False,False
3,26710,False,True,False,False,False,True,False,True,False,...,False,False,False,True,False,False,True,False,False,False
4,26711,False,False,False,True,False,True,False,False,True,...,False,True,True,False,False,False,False,True,False,False

In [34]:
# Keeping only the columns of train input in test
df2_filtered = df2[X.columns]

df2_filtered.head()

,xyz_concern_0.0,xyz_concern_1.0,xyz_concern_2.0,xyz_concern_3.0,xyz_knowledge_0.0,xyz_knowledge_1.0,behavioral_antiviral_meds_0.0,behavioral_avoidance_0.0,behavioral_face_mask_0.0,behavioral_wash_hands_0.0,...,employment_status_Unemployed,"census_msa_MSA, Principle City",census_msa_Non-MSA,household_adults_0.0,household_adults_2.0,household_adults_3.0,household_children_0.0,household_children_1.0,household_children_2.0,household_children_3.0
0,False,False,True,False,False,False,True,False,True,False,...,False,False,False,False,False,False,True,False,False,False
1,False,True,False,False,False,True,True,True,True,True,...,False,False,True,False,False,True,True,False,False,False
2,False,False,True,False,False,False,True,True,False,False,...,False,False,True,False,False,False,True,False,False,False
3,False,True,False,False,False,True,True,True,True,True,...,False,False,False,False,False,False,True,False,False,False
4,False,False,False,True,False,True,False,False,True,False,...,False,False,True,True,False,False,False,True,False,False

## Best Model traing and prediction as per train.ipynb

In [35]:
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.multioutput import MultiOutputClassifier
from sklearn.metrics import roc_auc_score

# Initialize the model
gb_model = MultiOutputClassifier(HistGradientBoostingClassifier(random_state=42))

# Train the model
gb_model.fit(X_train, y_train)

# Make predictions
gb_pred = gb_model.predict_proba(X_test)

# Extract the probabilities
xyz_vaccine_pred = gb_pred[0][:, 1]
seasonal_vaccine_pred = gb_pred[1][:, 1]

# Calculate the ROC AUC score
xyz_roc_auc = roc_auc_score(y_test['xyz_vaccine'], xyz_vaccine_pred, average='macro')
seasonal_roc_auc = roc_auc_score(y_test['seasonal_vaccine'], seasonal_vaccine_pred, average='macro')
print(xyz_roc_auc, seasonal_roc_auc)

# Compute the mean ROC AUC score
mean_roc_auc = (xyz_roc_auc + seasonal_roc_auc) / 2

print(f'HistGradientBoosting Mean ROC AUC Score: {mean_roc_auc}')

0.8496843356963567 0.8579272065167474
HistGradientBoosting Mean ROC AUC Score: 0.8538057711065521

In [36]:
# predictions on test data
# Make predictions
final_pred = gb_model.predict_proba(df2_filtered)

In [37]:
# Extract the probabilities
h1n1_vaccine = final_pred[0][:, 1]
seasonal_vaccine = final_pred[1][:, 1]

In [38]:
print(h1n1_vaccine, seasonal_vaccine)

[0.17438527 0.0260725  0.22760446 ... 0.16385918 0.02552042 0.59928342] [0.23099793 0.03453533 0.77297566 ... 0.15325903 0.16516412 0.58555135]

In [39]:
respondent_id = df2['respondent_id']

In [40]:
data = {
    'h1n1_vaccine': h1n1_vaccine,
    'seasonal_vaccine': seasonal_vaccine
}

df = pd.DataFrame(data)
df.index = respondent_id
df.head()

               h1n1_vaccine  seasonal_vaccine
respondent_id
26707              0.174385          0.230998
26708              0.026072          0.034535
26709              0.227604          0.772976
26710              0.549074          0.859990
26711              0.379407          0.406866

In [41]:
df.to_csv('final_output.csv')